name: Create Release

on:
    push:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup go
              uses: actions/setup-go@v3
              with:
                  go-version: 'stable'

            - name: test
              run: go test -v ./...

            - name: bump version
              id: version-bump
              uses: 'phips28/gh-action-bump-version@master'
              with:
                  tag-prefix: 'v'

            - name: set tagname
              id: tag
              run: echo "version=$(echo '${{ steps.version-bump.outputs.newTag }}' | sed 's/v//')" >> $GITHUB_OUTPUT

            - name: set major version name
              id: major_version
              run: echo "version=$(echo '${{ steps.version-bump.outputs.newTag }}' | sed 's/v//' | cut -d . -f 1)" >> $GITHUB_OUTPUT

            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.tag.outputs.newTag }}

            - name: create release branch
              uses: peterjgrainger/action-create-branch@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  branch: release-branch.${{ steps.major_version.outputs.version }}

            - name: merge to release branch
              uses: tukasz/direct-merge-action@v2.0.2
              with:
                  source-branch: main
                  target-branch: release-branch.${{ steps.major_version.outputs.version }}
                  commit-message: Automatic merge from main for release ${{ steps.tag.outputs.version }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
